/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedFournisseursRouteImport } from './routes/_authenticated/fournisseurs'
import { Route as AuthenticatedImportRouteImport } from './routes/_authenticated/import'
import { Route as AuthenticatedCatalogueIndexRouteImport } from './routes/_authenticated/catalogue.index'
import { Route as AuthenticatedCatalogueProduitIdRouteImport } from './routes/_authenticated/catalogue.$produitId'
import { Route as AuthenticatedChantiersIndexRouteImport } from './routes/_authenticated/chantiers.index'
import { Route as AuthenticatedChantiersChantierIdRouteImport } from './routes/_authenticated/chantiers.$chantierId'
import { Route as AuthenticatedFournisseursIndexRouteImport } from './routes/_authenticated/fournisseurs.index'
import { Route as AuthenticatedFournisseursFournisseurIdRouteImport } from './routes/_authenticated/fournisseurs.$fournisseurId'
import { Route as AuthenticatedRemplirMarcheIdRouteImport } from './routes/_authenticated/remplir.$marcheId'
import { Route as AuthenticatedRemplirMarcheIdRouteImport } from './routes/_authenticated/remplir.marcheId'
import { Route as AuthenticatedValidationChantierIdRouteImport } from './routes/_authenticated/validation.$chantierId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFournisseursRoute =
  AuthenticatedFournisseursRouteImport.update({
    id: '/fournisseurs',
    path: '/fournisseurs',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedImportRoute = AuthenticatedImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCatalogueIndexRoute =
  AuthenticatedCatalogueIndexRouteImport.update({
    id: '/catalogue/',
    path: '/catalogue/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCatalogueProduitIdRoute =
  AuthenticatedCatalogueProduitIdRouteImport.update({
    id: '/catalogue/$produitId',
    path: '/catalogue/$produitId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedChantiersIndexRoute =
  AuthenticatedChantiersIndexRouteImport.update({
    id: '/chantiers/',
    path: '/chantiers/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedChantiersChantierIdRoute =
  AuthenticatedChantiersChantierIdRouteImport.update({
    id: '/chantiers/$chantierId',
    path: '/chantiers/$chantierId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFournisseursIndexRoute =
  AuthenticatedFournisseursIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedFournisseursRoute,
  } as any)
const AuthenticatedFournisseursFournisseurIdRoute =
  AuthenticatedFournisseursFournisseurIdRouteImport.update({
    id: '/$fournisseurId',
    path: '/$fournisseurId',
    getParentRoute: () => AuthenticatedFournisseursRoute,
  } as any)
const AuthenticatedRemplirMarcheIdRoute =
  AuthenticatedRemplirMarcheIdRouteImport.update({
    id: '/remplir/$marcheId',
    path: '/remplir/$marcheId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRemplirMarcheIdRoute =
  AuthenticatedRemplirMarcheIdRouteImport.update({
    id: '/remplir/marcheId',
    path: '/remplir/marcheId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedValidationChantierIdRoute =
  AuthenticatedValidationChantierIdRouteImport.update({
    id: '/validation/$chantierId',
    path: '/validation/$chantierId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/fournisseurs': typeof AuthenticatedFournisseursRouteWithChildren
  '/import': typeof AuthenticatedImportRoute
  '/catalogue/$produitId': typeof AuthenticatedCatalogueProduitIdRoute
  '/chantiers/$chantierId': typeof AuthenticatedChantiersChantierIdRoute
  '/fournisseurs/$fournisseurId': typeof AuthenticatedFournisseursFournisseurIdRoute
  '/remplir/$marcheId': typeof AuthenticatedRemplirMarcheIdRoute
  '/remplir/marcheId': typeof AuthenticatedRemplirMarcheIdRoute
  '/validation/$chantierId': typeof AuthenticatedValidationChantierIdRoute
  '/catalogue/': typeof AuthenticatedCatalogueIndexRoute
  '/chantiers/': typeof AuthenticatedChantiersIndexRoute
  '/fournisseurs/': typeof AuthenticatedFournisseursIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/import': typeof AuthenticatedImportRoute
  '/catalogue/$produitId': typeof AuthenticatedCatalogueProduitIdRoute
  '/chantiers/$chantierId': typeof AuthenticatedChantiersChantierIdRoute
  '/fournisseurs/$fournisseurId': typeof AuthenticatedFournisseursFournisseurIdRoute
  '/remplir/$marcheId': typeof AuthenticatedRemplirMarcheIdRoute
  '/remplir/marcheId': typeof AuthenticatedRemplirMarcheIdRoute
  '/validation/$chantierId': typeof AuthenticatedValidationChantierIdRoute
  '/catalogue': typeof AuthenticatedCatalogueIndexRoute
  '/chantiers': typeof AuthenticatedChantiersIndexRoute
  '/fournisseurs': typeof AuthenticatedFournisseursIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/fournisseurs': typeof AuthenticatedFournisseursRouteWithChildren
  '/_authenticated/import': typeof AuthenticatedImportRoute
  '/_authenticated/catalogue/$produitId': typeof AuthenticatedCatalogueProduitIdRoute
  '/_authenticated/chantiers/$chantierId': typeof AuthenticatedChantiersChantierIdRoute
  '/_authenticated/fournisseurs/$fournisseurId': typeof AuthenticatedFournisseursFournisseurIdRoute
  '/_authenticated/remplir/$marcheId': typeof AuthenticatedRemplirMarcheIdRoute
  '/_authenticated/remplir/marcheId': typeof AuthenticatedRemplirMarcheIdRoute
  '/_authenticated/validation/$chantierId': typeof AuthenticatedValidationChantierIdRoute
  '/_authenticated/catalogue/': typeof AuthenticatedCatalogueIndexRoute
  '/_authenticated/chantiers/': typeof AuthenticatedChantiersIndexRoute
  '/_authenticated/fournisseurs/': typeof AuthenticatedFournisseursIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/dashboard'
    | '/fournisseurs'
    | '/import'
    | '/catalogue/$produitId'
    | '/chantiers/$chantierId'
    | '/fournisseurs/$fournisseurId'
    | '/remplir/$marcheId'
    | '/remplir/marcheId'
    | '/validation/$chantierId'
    | '/catalogue/'
    | '/chantiers/'
    | '/fournisseurs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin'
    | '/dashboard'
    | '/import'
    | '/catalogue/$produitId'
    | '/chantiers/$chantierId'
    | '/fournisseurs/$fournisseurId'
    | '/remplir/$marcheId'
    | '/remplir/marcheId'
    | '/validation/$chantierId'
    | '/catalogue'
    | '/chantiers'
    | '/fournisseurs'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/_authenticated/dashboard'
    | '/_authenticated/fournisseurs'
    | '/_authenticated/import'
    | '/_authenticated/catalogue/$produitId'
    | '/_authenticated/chantiers/$chantierId'
    | '/_authenticated/fournisseurs/$fournisseurId'
    | '/_authenticated/remplir/$marcheId'
    | '/_authenticated/remplir/marcheId'
    | '/_authenticated/validation/$chantierId'
    | '/_authenticated/catalogue/'
    | '/_authenticated/chantiers/'
    | '/_authenticated/fournisseurs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fournisseurs': {
      id: '/_authenticated/fournisseurs'
      path: '/fournisseurs'
      fullPath: '/fournisseurs'
      preLoaderRoute: typeof AuthenticatedFournisseursRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/import': {
      id: '/_authenticated/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof AuthenticatedImportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/catalogue/': {
      id: '/_authenticated/catalogue/'
      path: '/catalogue'
      fullPath: '/catalogue/'
      preLoaderRoute: typeof AuthenticatedCatalogueIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/catalogue/$produitId': {
      id: '/_authenticated/catalogue/$produitId'
      path: '/catalogue/$produitId'
      fullPath: '/catalogue/$produitId'
      preLoaderRoute: typeof AuthenticatedCatalogueProduitIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chantiers/': {
      id: '/_authenticated/chantiers/'
      path: '/chantiers'
      fullPath: '/chantiers/'
      preLoaderRoute: typeof AuthenticatedChantiersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chantiers/$chantierId': {
      id: '/_authenticated/chantiers/$chantierId'
      path: '/chantiers/$chantierId'
      fullPath: '/chantiers/$chantierId'
      preLoaderRoute: typeof AuthenticatedChantiersChantierIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fournisseurs/': {
      id: '/_authenticated/fournisseurs/'
      path: '/'
      fullPath: '/fournisseurs/'
      preLoaderRoute: typeof AuthenticatedFournisseursIndexRouteImport
      parentRoute: typeof AuthenticatedFournisseursRoute
    }
    '/_authenticated/fournisseurs/$fournisseurId': {
      id: '/_authenticated/fournisseurs/$fournisseurId'
      path: '/$fournisseurId'
      fullPath: '/fournisseurs/$fournisseurId'
      preLoaderRoute: typeof AuthenticatedFournisseursFournisseurIdRouteImport
      parentRoute: typeof AuthenticatedFournisseursRoute
    }
    '/_authenticated/remplir/$marcheId': {
      id: '/_authenticated/remplir/$marcheId'
      path: '/remplir/$marcheId'
      fullPath: '/remplir/$marcheId'
      preLoaderRoute: typeof AuthenticatedRemplirMarcheIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/remplir/marcheId': {
      id: '/_authenticated/remplir/marcheId'
      path: '/remplir/marcheId'
      fullPath: '/remplir/marcheId'
      preLoaderRoute: typeof AuthenticatedRemplirMarcheIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/validation/$chantierId': {
      id: '/_authenticated/validation/$chantierId'
      path: '/validation/$chantierId'
      fullPath: '/validation/$chantierId'
      preLoaderRoute: typeof AuthenticatedValidationChantierIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedFournisseursRouteChildren {
  AuthenticatedFournisseursFournisseurIdRoute: typeof AuthenticatedFournisseursFournisseurIdRoute
  AuthenticatedFournisseursIndexRoute: typeof AuthenticatedFournisseursIndexRoute
}

const AuthenticatedFournisseursRouteChildren: AuthenticatedFournisseursRouteChildren =
  {
    AuthenticatedFournisseursFournisseurIdRoute:
      AuthenticatedFournisseursFournisseurIdRoute,
    AuthenticatedFournisseursIndexRoute: AuthenticatedFournisseursIndexRoute,
  }

const AuthenticatedFournisseursRouteWithChildren =
  AuthenticatedFournisseursRoute._addFileChildren(
    AuthenticatedFournisseursRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedFournisseursRoute: typeof AuthenticatedFournisseursRouteWithChildren
  AuthenticatedImportRoute: typeof AuthenticatedImportRoute
  AuthenticatedCatalogueProduitIdRoute: typeof AuthenticatedCatalogueProduitIdRoute
  AuthenticatedChantiersChantierIdRoute: typeof AuthenticatedChantiersChantierIdRoute
  AuthenticatedRemplirMarcheIdRoute: typeof AuthenticatedRemplirMarcheIdRoute
  AuthenticatedRemplirMarcheIdRoute: typeof AuthenticatedRemplirMarcheIdRoute
  AuthenticatedValidationChantierIdRoute: typeof AuthenticatedValidationChantierIdRoute
  AuthenticatedCatalogueIndexRoute: typeof AuthenticatedCatalogueIndexRoute
  AuthenticatedChantiersIndexRoute: typeof AuthenticatedChantiersIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedFournisseursRoute: AuthenticatedFournisseursRouteWithChildren,
  AuthenticatedImportRoute: AuthenticatedImportRoute,
  AuthenticatedCatalogueProduitIdRoute: AuthenticatedCatalogueProduitIdRoute,
  AuthenticatedChantiersChantierIdRoute: AuthenticatedChantiersChantierIdRoute,
  AuthenticatedRemplirMarcheIdRoute: AuthenticatedRemplirMarcheIdRoute,
  AuthenticatedRemplirMarcheIdRoute: AuthenticatedRemplirMarcheIdRoute,
  AuthenticatedValidationChantierIdRoute:
    AuthenticatedValidationChantierIdRoute,
  AuthenticatedCatalogueIndexRoute: AuthenticatedCatalogueIndexRoute,
  AuthenticatedChantiersIndexRoute: AuthenticatedChantiersIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
